### ISSUE TITLE
Javascript files not found

### ISSUE THREAD

**Issue by joosev** [Pakettikauppa/woo-pakettikauppa#103]
In some cases, admin and checkout javascript files are not loaded.

"ReferenceError: pakettikauppa_change_method is not defined onclick" (WordPress 4.912 and woocommerce 3.7)

regarding screenshot: Wordpress version WordPress 5.2.4, Woocommerce 3.8.0, Pakettikauppa Version 2.1.

![Näyttökuva 2019-11-28 kello 12 07 39](https://user-images.githubusercontent.com/14106091/69797077-c6d96c00-11d7-11ea-873c-d2f8e4b6a8fb.png)

**Comment by k1sul1** [comment]
If the javascript files were actually missing, there would be a 404 error in the console about that. This looks more like a "race condition". The scripts are loaded in the end of the body (as they should be), but for some reason they haven't loaded before you clicked a button with an inline event listener.

Inline event listeners belong in the year 2000, and there's really no point in using them, but removing them requires a partial rewrite of the JS.
