### ISSUE TITLE
Exception goes uncaughted

### ISSUE THREAD

**Issue by joosev** [Pakettikauppa/woo-pakettikauppa#104]
![4f6c47e35dc3a652184e359e707201a587d89c8d](https://user-images.githubusercontent.com/14106091/69798481-0f922480-11da-11ea-8415-cf30488a04c0.jpeg)

**Comment by joosev** [comment]
This seems to be related when creating multiple shipments from "orders" view.

**Comment by joosev** [comment]
This bug is becoming a problem in our customer service.

**Comment by joosev** [comment]
![8ea2ed13d18a6a736ea933313d7af5ebab820b70](https://user-images.githubusercontent.com/14106091/70695570-b68eba00-1cca-11ea-9bd0-ba6440316ec4.png)

**Comment by k1sul1** [comment]
I can't reproduce this without more information. I did some changes but they shouldn't have affected this.

I created an order and set Gibraltar as the country. Exceptions work as intended if I try to create a label from the order manage screen. 

![image](https://user-images.githubusercontent.com/2719615/70917187-8f671e00-2025-11ea-90e9-6c368869502d.png)

When I tried the "Create and fetch shipping labels" bulk action, I got an error, but this seems intentional. 

![image](https://user-images.githubusercontent.com/2719615/70917467-10beb080-2026-11ea-8fae-9a60f7c233d9.png)

```php
public function create_multiple_shipments() {
  if ( ! isset($_REQUEST['post']) ) {
    return;
  }

  if ( ! is_array($_REQUEST['post']) ) {
    return;
  }

  $action = null;

  if ( isset($_REQUEST['action']) && $_REQUEST['action'] !== '-1' ) {
    $action = $_REQUEST['action'];
  } elseif ( isset($_REQUEST['action2']) && $_REQUEST['action2'] !== '-1' ) {
    $action = $_REQUEST['action2'];
  }

  if ( $action === null ) {
    return;
  }

  if ( ! ($action === str_replace('wc_', '', $this->core->prefix) . '_create_multiple_shipping_labels' || $action === 'quick_create_label') ) {
    return;
  }

  if ( ! wp_verify_nonce(sanitize_key($_REQUEST['_wpnonce']), 'bulk-posts') ) {
    return;
  }

  $tracking_codes = $this->create_shipments($_REQUEST['post']);

  $contents = $this->fetch_shipping_labels($tracking_codes);

  if ( $contents->{'response.file'}->__toString() === '' ) {
    esc_attr_e('Cannot find shipments with given shipment numbers.', 'woo-pakettikauppa');

    return;
  }

  $this->output_shipping_label($contents, 'multiple-shipping-labels');
}
```

I also created two "valid" orders, that both used different delivery methods, and tried using the bulk action. It worked as expected: 

![image](https://user-images.githubusercontent.com/2719615/70917985-fdf8ab80-2026-11ea-9ade-a26ea947bee8.png)

**Comment by joosev** [comment]
Related to issue #111

**Comment by joosev** [comment]
Something is different - don't know what.

When exception is thrown, it is shown to merchants and/or is sent by the email to the merchant (if new enough wordpress then email is sent).

**Comment by joosev** [comment]
Seems like try { } catch {Exception $e} does not work in PHP 7.x anymore and try {} catch (Throwable $e) should be used instead.

https://www.php.net/manual/en/language.errors.php7.php

That might cause the problem

**Comment by k1sul1** [comment]
`catch (\Exception $e)` works just as in previous versions. AFAIK the codebase throws only `\Exception`s. There shouldn't be any PHP errors.

**Comment by joosev** [comment]
Might be. It's weird that code has like this:

      try {
        $shipment = $this->create_shipment_from_order($order, $service_id, $additional_services);
        $tracking_code = $shipment->{'response.trackingcode'}->__toString();
      } catch ( \Exception $e ) {
        $this->add_error($e->getMessage());
        /* translators: %s: Error message */
        $order->add_order_note(sprintf(esc_attr__('Failed to create Pakettikauppa shipment. Errors: %s', 'woo-pakettikauppa'), $e->getMessage()));
        add_action(
          'admin_notices',
          function() use ( $e ) {
            /* translators: %s: Error message */
            $this->add_error_notice(wp_sprintf(esc_attr__('An error occured: %s', 'woo-pakettikauppa'), $e->getMessage()));
          }
        );
        return null;
      }

Yet, exceptions coming through:

        $shipment = $this->create_shipment_from_order($order, $service_id, $additional_services);

and is catched with catch (\Exception $e) yet.. is not and is shown to browser and an email is sent.

**Comment by k1sul1** [comment]
That try/catch is there to catch `throw new \Exception(wp_sprintf(__('WooCommerce Pakettikauppa: tracking code creation failed: %s', 'woo-pakettikauppa'), $e->getMessage()));` that `$this->create_shipment_from_order` may throw. It doesn't throw any other exceptions, I looked at every class it initiates. Correct me if I'm wrong but I digged pretty deep.

If any of the underlying code results in a PHP error under X circumstances (I don't know of any), it will fall through that catch and cause a fatal error screen like in your screenshot, but it would be a different error, and not an actual Exception that was thrown from the code. 

In other words, I think that there's nothing wrong with the code (regarding this matter). Catch-all catches smell bad, a PHP error shouldn't fall in a catch unless the purpose is to spesifically deal with some misbehaviour on different versions of PHP.

`$admin->save_ajax_metabox` uses `$admin->create_return_label` which uses `$shipment->create_shipment_from_order` and doesn't include a try / catch for the potential `Exception` I mentioned earlier, so trying to create a return label might cause this behaviour, but I don't understand why it would, and if it would, the error message should be inside the metabox, not as shown in your screenshot.

When I added namespaces to this plugin, I used search & replace. It missed some `catch (Exception $e)` blocks for some reason, which resulted in it catching only `Woo_Pakettikauppa_Core\Exception`s, which are non-existent. I can't remember when exactly I fixed that, but before I did that, I believe it would've behaved the same way as your first screenshot. Are the problematic instances actually running the latest version or something older?

We have a nice case of "this can't happen" on our hands, but clearly it's happening?

**Comment by k1sul1** [comment]
I'd recommend releasing 2.2 tomorrow to ensure that everyone is running the latest version, a lot has changed since the last release. I think this issue will disappear after doing that.

@joosev ok?

**Comment by k1sul1** [comment]
I did some digging. I fixed the faulty catches 14 days ago, and last release was 20 days ago. I doubt the users who are reporting this are using the master branch build.

Where the problem started
https://github.com/Seravo/woo-pakettikauppa/tree/0d4b73cdeb678ad56d0b47b9884326395fe21880

After fix
https://github.com/Seravo/woo-pakettikauppa/tree/bea2f911349396774040efd3ab4e461b52e61e73

PHPCS probably should've complained about the non-existence of `Woo_Pakettikauppa_Core\Exception`, but it didn't, static analysis tools need some reconfiguration. I added the important label to #15, we need to prevent these kind of bugs from happening.

Changelog for changes after the latest release

- Properly catch exceptions
- Allow supplying a different address for pickup point search
- Fix headers so files download properly

**Comment by joosev** [comment]
No one is using master branch version.

**Comment by k1sul1** [comment]
2.2 is out. I'm keeping this issue open for now but it was fixed over two weeks ago.

**Comment by k1sul1** [comment]
I'm assuming the latest upgrade fixed it as suspected. Reopen if issue persists.
