### ISSUE TITLE
Legacy shipping method optional to config

### ISSUE THREAD

**Issue by joosev** [Pakettikauppa/woo-pakettikauppa#105]
Make legacy shipping method optional so that whitelabel plugin can choose not to use it.

**Comment by k1sul1** [comment]
Wouldn't removing the legacy shipping method entirely make more sense? #94 requires a breaking change, so the removal should be done for 3.0.

**Comment by joosev** [comment]
Yes it would. Let's make a big notice "use another shipping method" that need to be dismissed if someone is using legacy method.

**Comment by joosev** [comment]
Create alert for next version that this will be removed in the next version.

And in the version after that let's remove it and call it 3.0
