### ISSUE TITLE
Changing method from Parcel Connect to Noutopisteet causes error

### ISSUE THREAD

**Issue by joosev** [Pakettikauppa/woo-pakettikauppa#108]
TypeError: null is not an object (evaluating 'document.getElementById(methodId + '-' + strUser + '-services').style')

**Comment by k1sul1** [comment]
HTML element IDs can't start with a number. The selector is invalid and thus returns null for no element. Fixing this requires changing the IDs, but since this doesn't break anything (?) it's not very high priority. I'll take a look if I have time later this week.

**Comment by joosev** [comment]
error comes when there are no additional sevices available for the selected shipping method and so it is tried to do something that does not exists.

Not very important issue. Does not break anything.
