### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by joosev** [Pakettikauppa/woo-pakettikauppa#109]
Should say: "Selaimeen":
![Näyttökuva 2019-12-2 kello 15 46 46](https://user-images.githubusercontent.com/14106091/69964410-0b883e80-151b-11ea-9c51-f27373ab4572.png)

Should say between the () "Sisältää noutopisteet"
![Näyttökuva 2019-12-2 kello 15 46 57](https://user-images.githubusercontent.com/14106091/69964416-0e832f00-151b-11ea-86f3-601d49442faf.png)

**Comment by k1sul1** [comment]
Fixed at some unknown point in time. Translated in 2.2
