### ISSUE TITLE
Show more pickup locations

### ISSUE THREAD

**Issue by joosev** [Pakettikauppa/woo-pakettikauppa#11]
According to real world use data, display 10 closest pickup locations is better than displaying 5. Of course if this could be configured by admin in settings, even better. But I think 10 closest picukup points is good for all.

**Comment by l3ku** [comment]
In my understanding the Pakettikauppa API does not support this, as the only parameters for pickup point search are postcode, country, street address and service provider (see https://github.com/Pakettikauppa/api-library/blob/7bce84c475c68c69269613500d2e7bd8a1fe0c2f/src/Pakettikauppa/Client.php#L148). If an additional parameter for the number of pickup points is added, more results can be shown.

**Comment by joosev** [comment]
seems to be undocumented feature.. I have a feeling that Client.php will support limit parameter soon.

**Comment by joosev** [comment]
It is now documented and fixed in api-library!

**Comment by l3ku** [comment]
Support for limiting the amount of pickup points is added in bd52422. The user can now specify the limit in Pakettikauppa settings located in WooCommerce shipping settings.
