### ISSUE TITLE
When creating shipments, error messages are not in order notes anymore

### ISSUE THREAD

**Issue by joosev** [Pakettikauppa/woo-pakettikauppa#111]
For example:

web_1  | 2019/12/04 07:33:58 [error] 67#67: *112 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: Error: 230, Bad Request: Selected pickup point not available for COD shipments. in /app/wp-content/plugins/woo-pakettikauppa/vendor/pakettikauppa/api-library/src/Pakettikauppa/Client.php:87
web_1  | Stack trace:
web_1  | #0 /app/wp-content/plugins/woo-pakettikauppa/core/class-shipment.php(558): Pakettikauppa\Client->createTrackingCode(Object(Pakettikauppa\Shipment))
web_1  | #1 /app/wp-content/plugins/woo-pakettikauppa/core/class-shipment.php(202): Woo_Pakettikauppa_Core\Shipment->create_shipment_from_order(Object(WC_Order), '2103', Array)
web_1  | #2 /app/wp-content/plugins/woo-pakettikauppa/core/class-admin.php(760): Woo_Pakettikauppa_Core\Shipment->create_shipment(Object(WC_Order), '2103', Array)
web_1  | #3 /app/wp-content/plugins/woo-pakettikauppa/core/class-admin.php(118): Woo_Pakettikauppa_Core\Admin->save_ajax_metabox('93')
web_1  | #4 /app/wp-includes/class-wp-hook.php(286): Woo_Pakettikauppa_Core\Admin->ajax_meta_box('')

But nothing is shown here:
![Näyttökuva 2019-12-4 kello 9 35 32](https://user-images.githubusercontent.com/14106091/70122504-6d5eba80-1679-11ea-86bd-4a13c46fec81.png)

**Comment by joosev** [comment]
More examples:

"Tiedoston /home/xxxxx/public_html/wp-content/plugins/woo-pakettikauppa/vendor/pakettikauppa/api-library/src/Pakettikauppa/Client.php rivillä 87 havaittiin virhe lajia E_ERROR. Virheviesti: Uncaught Exception: Error: 240, Insufficient balance in /home/xxxxx/public_html/wp-content/plugins/woo-pakettikauppa/vendor/pakettikauppa/api-library/src/Pakettikauppa/Client.php:87

Stack trace:

#0 /home/xxxxx/public_html/wp-content/plugins/woo-pakettikauppa/core/class-shipment.php(558): Pakettikauppa\Client->createTrackingCode(Object(Pakettikauppa\Shipment))
#1 /home/xxxxx/public_html/wp-content/plugins/woo-pakettikauppa/core/class-shipment.php(202): Woo_Pakettikauppa_Core\Shipment->create_shipment_from_order(Object(WC_Order), '2461', Array)
#2 /home/xxxxx/public_html/wp-content/plugins/woo-pakettikauppa/core/class-admin.php(321): Woo_Pakettikauppa_Core\Shipment->create_shipment(Object(WC_Order))
#3 /home/xxxxx/public_html/wp-content/plugins/woo-pakettikauppa/core/class-admin.php(296): Woo_Pakettikauppa_Core\Admin->create_shipments(Array)
#4 /home/xxxxx/public_html/wp-includes/class-wp-hook.php(290): Woo_Pakettikauppa_Core\Admin->create_multiple_shipments('/wp-admin/edit....')
#5 /home/mets

**Comment by joosev** [comment]
Related to #104

**Comment by k1sul1** [comment]
I'm assuming the latest upgrade fixed it as suspected. Reopen if issue persists.
