### ISSUE TITLE
Settings are not saving

### ISSUE THREAD

**Issue by joosev** [Pakettikauppa/woo-pakettikauppa#112]
When trying to save settings, settings are not saved. process_admin_options is not called.

Wizard will run ok and save values, but after that, nothing on the settings page can be changed.

I can't replicate this myself, but I have had access to two different woo installation that shows this behaviour.

**Comment by joosev** [comment]
Both running 2.1.2 of the plugin.

**Comment by joosev** [comment]
2.0.22 works ok in the same store

**Comment by joosev** [comment]
Seems to be related to WPML.

If "WPML String Translation" and "WPML Translation Management" plugins are installed, settings are not saved.

**Comment by joosev** [comment]
When using those plugins, shipping methods are registered later than WPML is loaded. So that seems to cause the translating of the values/something not to register our shipping method class at all and that is why the filter is never called because get_shipping_methods() function does not know that our shipping module exists.

Solving this might need contacting wpml.

**Comment by joosev** [comment]
If neather one of those plugins are disabled, then our shipping method plugin is loaded earlier and then get_shipping_methods() will return also our shipping method and process_admin_options() is called.

**Comment by joosev** [comment]
In Core class, if we don't use "        add_action(
        'wp_loaded',
        function() {
"

and don't use WC() in the settings defaults, then it works ok.


If I change the forms like this:

        'default' => $this->settings_get_base_city(),

and then do like this:

      public $base_address = '';
      public $base_postcode = '';
      public $base_city = '';

      private function settings_get_base_address() {
        return $this->base_address;
      }
      private   function settings_get_base_postcode() {
          return $this->base_postcode;
      }
      private  function settings_get_base_city() {
          return $this->base_city;
      }


And then in Core do like this:

        $this->shipping_method_instance = $this->load_shipping_method_class();
        $this->add_shipping_method();

        add_action(
        'wp_loaded',
        function() {
            $this->shipping_method_instance->base_address = WC()->countries->get_base_address();
            $this->shipping_method_instance->base_city = WC()->countries->get_base_city();
            $this->shipping_method_instance->base_postcode = WC()->countries->get_base_postcode();
            // Instance is only used for hacking classes together.
          // It's not used by WooCommerce. WooCommerce creates it's own instances, otherwise the legacy
          // shipping method breaks. If this class doesn't contain the shipping method class instance
          // things like setup wizard break.
        }, 1
      );


It seems to work. But did not test that much.

**Comment by k1sul1** [comment]
If I had to guess, I'd guess that WPML does stuff in wp_loaded and the code in this plugin runs before that. If that's the case, it can probably be fixed with priority parameter to add_action.

**Comment by joosev** [comment]
I tried it, but didn't have any effect. Or I did not know how to use priority. As you can see in this example I have posted, I tried priority 1, but I also tried 10000 and -10000

**Comment by k1sul1** [comment]
I'm hoping this one goes away with the latest update. If not, I need copies of the plugins mentioned earlier.

**Comment by k1sul1** [comment]
I'm assuming the latest upgrade fixed it as suspected. Reopen if issue persists.

**Comment by joosev** [comment]
Problem still exists.

**Comment by joosev** [comment]
Small change made to logic, let's see if it fixes the problem
