### ISSUE TITLE
Does not work with klarna

### ISSUE THREAD

**Issue by joosev** [Pakettikauppa/woo-pakettikauppa#120]
Currently if payment method is Klarna, pickup point chooser is not visible.

![Näyttökuva 2020-1-8 kello 14 15 31](https://user-images.githubusercontent.com/14106091/71977608-e8d7fc80-3221-11ea-97ba-771cb02c9981.png)
![Näyttökuva 2020-1-8 kello 14 15 17](https://user-images.githubusercontent.com/14106091/71977610-e9709300-3221-11ea-937d-e4c2dc40ed7c.png)
![Näyttökuva 2020-1-8 kello 14 15 09](https://user-images.githubusercontent.com/14106091/71977612-e9709300-3221-11ea-8e86-2bee659f16eb.png)

Possible fixes:
- show pickup point chooser on the "Pikakassa" page.
- show pickup point chooser on summary page.

**Comment by ottok** [comment]
Thanks for reporting!

**Comment by k1sul1** [comment]
Klarna plugin doesn't work without test credentials, which are unique to each Klarna customer, and I can't get those as I'm not a customer of Klarna.

If someone can provide me some api keys to the test api, I can "debug" this later in this month.  It's not a bug as the pickup point chooser has never been on the cart page, it's in checkout, and Klarna replaces that page. Fixing it is going to require a flow change.
