### ISSUE TITLE
Real shipping costs calculator

### ISSUE THREAD

**Issue by joosev** [Pakettikauppa/woo-pakettikauppa#126]
This is a bigger feature.

As a merchant, I want to offer dynamic prices for shipments that are calculated from real costs. I also like to adjust prices to add or subtract absolute euro values or percent values. I also want to round values to nice values.

Use case for "Adding some price to real price": I want to add 5e as packaging costs to each shipment.

Use case for "Changing price to percent": I want as a merchant to pay half of the shipping costs.

Pakettikauppa API has a feature to allow realtime calculation of the shipping prices. This is supported in the dev-branch of the api-library.

UI could have options like:
1. "Add/subtract euros or percents"

Somehow we need to be able to inject new price for the shipping method.

First task:
- investigate and report the implementation solutions for this problem

**Comment by k1sul1** [comment]
[Getting the price seems trivial](https://github.com/Pakettikauppa/api-library/blob/dev/examples/estimate-price.php) after calculating the package dimensions which is the hard part.

Adding modifiers to that price is also trivial, but building an UI for it takes time, probably longer than the monthly quota for the project. 

When is that feature going to be released?  I wouldn't include a dev library in a production plugin.

**Comment by joosev** [comment]
Let's keep this for now here and implement later. We will try to publish 2.0 version of the api-library that will have this feature.

**Comment by joosev** [comment]
This is now in 2.0 api library

    public function estimateShippingCost(Shipment &$shipment)

**Comment by joosev** [comment]
This is difficult in the sense that almost all shipping methods are priced based on volume based weight and not weight (unless weight is more)... So! This can be done based on product weights, but we have to tell users that pricing is done based on product weights and not volume and that we have to give some option for users to add a minimun weight or some sort of multiplier to weight or something that merchants can estimate themselves the difference between volumeweight and weight.

Sidenote: Weight based on volume is most of the time calculated by X m * Y m * Z m * 250 kg/m^3 but it is something the plugin does not need to know.
