### ISSUE TITLE
Some themes break CSS of the select-option elements

### ISSUE THREAD

**Issue by joosev** [Pakettikauppa/woo-pakettikauppa#128]
Under some theme it looks like this:

![Screen Shot 2020-02-05 at 11 22 21](https://user-images.githubusercontent.com/14106091/74339254-686e6380-4dac-11ea-9d0d-0376bcc9c372.png)

Default theme looks ok:
![Näyttökuva 2020-2-12 kello 13 10 49](https://user-images.githubusercontent.com/14106091/74339296-7c19ca00-4dac-11ea-9452-5b5c1dacbf87.png)
![Näyttökuva 2020-2-12 kello 13 09 31](https://user-images.githubusercontent.com/14106091/74339305-8045e780-4dac-11ea-94be-8c21c64e9b08.png)

Question is: can we make sure that we have correct CSS hard coded to the element or should we just ignore the problem and ask the merchants to fix their themes css?

**Comment by k1sul1** [comment]
IMO it's not broken. It's what the theme author designed, even if it looks silly. The first screenshot is clearly stretching the second column of the table to maximum width which then overflows, not much to do here. 

If I maintained a website and a plugin update changed the way I made things look, I would be absolutely furious if a plugin overwrote my styles.

**Comment by joosev** [comment]
OK
