### ISSUE TITLE
Test api credentials

### ISSUE THREAD

**Issue by joosev** [Pakettikauppa/woo-pakettikauppa#130]
Test API credentials button

OR

When the API credentials are saved, we test that if it works or not and display the result next to API key & secret and if it's not working -> display error message.

**Comment by k1sul1** [comment]
Test against what? I skimmed through the [documentation](https://www.pakettikauppa.fi/wp-content/uploads/ODD-121119-0724.pdf) and I couldn't find anything to validate them against. 

WooCommerce automatically calls these functions if they exist, they can be used to throw errors or the like, but ATM I have nothing to put into those. 
```
    public function validate_account_number_field($key, $value) {

    }

    public function validate_secret_key_field($key, $value) {

    }
```

**Comment by joosev** [comment]
Would it work if it would Call list shipping methods api end point?

**Comment by k1sul1** [comment]
Maybe. I can't use those functions for validating if I use the list shipping methods endpointm but I'll try to work something out.
