### ISSUE TITLE
Possible bug when integrating with Klarna

### ISSUE THREAD

**Issue by joosev** [Pakettikauppa/woo-pakettikauppa#132]
This order was made as a fallback due to an error in the checkout (Error message: Noutopistettä ei ole valittu.). Please verify the order with Klarna.

So it seems that user can proceed without choosing a pickup point.

**Comment by k1sul1** [comment]
Klarna's developers cut a lot of corners for their plugin. It doesn't run `woocommerce_checkout_process` action which is used to validate the checkout.

Making the select field required would not help either, as the actual checkout form is in an external iframe. It's not possible to add event listeners to it. 

Can't fix until Klarna fixes theirs. I looked at their source and tried hooking into `kco_validate_checkout` but no luck.

**Comment by joosev** [comment]
Hmm.. what if we automatically select first pickup point in these cases?

**Comment by k1sul1** [comment]
Done.
