### ISSUE TITLE
Test compatibility with WooCommerce 4.0

### ISSUE THREAD

**Issue by ottok** [Pakettikauppa/woo-pakettikauppa#136]
WooCommerce 4.0 will be released in March 2020. The release candidate is already out. This plugin should be tested with WooCommerce 4.0 and possible compatibility issues documented and addressed.

**Comment by ottok** [comment]
Ideally the WooCommerce version in the testing scrpts would be a parameter so the unit tests could run against multiple WooCommerce versions in parallel.

**Comment by k1sul1** [comment]
Seems to work just fine in 4.0. Tested while doing #139.
