### ISSUE TITLE
Cannot activate production mode

### ISSUE THREAD

**Issue by eddiemackie** [Pakettikauppa/woo-pakettikauppa#139]
We ran into a situation where the WPML extension called WooCommerce multilingual prevents the Pakettikauppa plugin from being set to poduction mode. 

The API credentials can be saved and testing mode activates, but production mode cannot be activated. 

I tested this out in multiple ways, and the production mode could be activated every time, except when the WooCommerce multilingual plugin was active. Here's the plugin in question: https://wordpress.org/plugins/woocommerce-multilingual/

A quick fix for this seems to be disabling the WooCommerce multilingual plugin for a moment when putting Pakettikauppa into production mode, then re-activating the plugin. Did not test if everything works as expected with Pakettikauppa if using this fix though.

**Comment by joosev** [comment]
Related to #112 

Is any settings saved when that plugin is installed?

**Comment by eddiemackie** [comment]
> Related to #112
> 
> Is any settings saved when that plugin is installed?

Tested and you are correct, no settings are saved when WooCommerce multilingual is active. 

Deactivated WooCommerce multilingual and left WPML and its other extension active, settings are saved.

**Comment by ooksanen** [comment]
Can confirm, deactivating only WooCommerce multilingual is sufficient to save settings, no need to deactivate WPML itself or any other extensions. 

Also, the setup wizard seems to save everything properly even with WooCommerce multilingual active.

**Comment by k1sul1** [comment]
@EddieFin can you recall what the WooCommerce version was 19 days ago? It's 4.0.0 now and I can't reproduce the issue on a clone from production. 

edit: for the record, I can't reproduce it even after downgrading to 3.9. WooCommerce multilingual is active, version 4.7.9. It can be updated to 4.8.0 but it seems to work as is.

**Comment by ooksanen** [comment]
> what the WooCommerce version was 19 days ago?

3.9.2

**Comment by k1sul1** [comment]
Updated everything (except WPML, because I don't have licences) in my local copy to the latest version, and then tested the checkout, shipment creation etc, it all works as expected.

Closing. Open the issue again if the problem appears elsewhere.
