### ISSUE TITLE
Possible to print out a slip from the order page?

### ISSUE THREAD

**Issue by Rubberduckweb** [Pakettikauppa/woo-pakettikauppa#17]
Would it be possible to be able to print the shipping stickers with all the info from the main order pages. Maybe a icon like these?

<img width="189" alt="screen shot 2017-12-07 at 19 31 01" src="https://user-images.githubusercontent.com/34348634/33729144-63d67b46-db85-11e7-977a-b1be3feb4ac3.png">

**Comment by joosev** [comment]
Here is a code example of that feature. https://stackoverflow.com/questions/45516819/add-a-custom-action-button-in-woocommerce-admin-order-list

**Comment by joosev** [comment]
Implemented in 2.0 -series
