### ISSUE TITLE
Error when creating multiple shipments 

### ISSUE THREAD

**Issue by pohjaton** [Pakettikauppa/woo-pakettikauppa#175]
https://github.com/Seravo/woo-pakettikauppa/blob/a896f3dac44d026864058c8ec1414f87e6dff784/core/class-admin.php#L328

Fixed it by removing invalid part

$tracking_codes = $this->create_shipments($_REQUEST['post']);

**Comment by joosev** [comment]
Seems like you are using HEAD version of the plugin. It's still work in progress, but there was an error in that input validation function call and will be fixed and more validation is still on it's way.
