### ISSUE TITLE
Pricing per shipping method

### ISSUE THREAD

**Issue by joosev** [Pakettikauppa/woo-pakettikauppa#18]
There should be possibility to add different prices for different shipping methods and/or providers.

**Comment by ottok** [comment]
This seems to be a high priority.

**Comment by joosev** [comment]
Maybe something like this.

![nayttokuva 2017-12-12 kello 15 12 12](https://user-images.githubusercontent.com/14106091/33886513-7ebe8822-df4f-11e7-9be0-d1de86a3edf0.png)

**Comment by joosev** [comment]
There is a fix for this as pull request

**Comment by joosev** [comment]
This also fixes issue #12

**Comment by tatusah** [comment]
To be truly compatible with the Woocommerce shipping zones shouldn't Pakettikauppa be an option in the shipping zone shipping method dropdown?

![image](https://user-images.githubusercontent.com/17417945/34036156-fd73b07c-e18c-11e7-95d9-78955e545b02.png)


And thinking about the future maybe actually all the shipping methods included in Pakettikauppa should be available individually here. This would give later on the possibility to make smaller local shipping providers available based on the customer ZIP/postcode by using the Woocommerce core functionality related to these zone based shipping methods.

**Comment by joosev** [comment]
Yes, shipping zones support is something that we are implementing in the future. Have to do little bit research on this Woo Shipping Zones issue to see how well it can be adapted to this one provider, multiple shipping methods scenario.

**Comment by l3ku** [comment]
What is the status of this issue? After the plugin has been refactored to support Woo Shipping Zones in 4fe8cb3ec3a9c280a73efd7201b645fc6be9950f, is it now possible to specify different rates for different Pakettikauppa shipping method providers?

**Comment by joosev** [comment]
This is solved.
