### ISSUE TITLE
Show a setup wizard when activating the plugin

### ISSUE THREAD

**Issue by l3ku** [Pakettikauppa/woo-pakettikauppa#20]
The setup wizard could guide the user on the necessary configuration steps, like asking if the merchant already has a shipping contract and configuring the plugin settings based on this information. This way, the plugin activation process would be as simple and fast as possible for the end user.

**Comment by l3ku** [comment]
My development efforts towards creating a setup wizard are in currently viewable at https://github.com/Seravo/woo-pakettikauppa/tree/feature/setup-wizard. 

The current UI design is heavily influenced by the WooCommerce setup wizard:
![Screen Shot 2019-08-23 at 12 57 43](https://user-images.githubusercontent.com/24781811/63584810-65857980-c5a6-11e9-9701-a4c69ee1a503.png)

I am not sure about what steps would be the best for the wizard, so currently I have implemented only the filling of settings in the plugin WooCommerce shipping settings page. What is your opinion about the best possible setup wizard steps @joosev? Should we add our custom step that adds Pakettikauppa as a shipping method into some currently active shipping zone, or should we just resort to linking to the WooCommerce shipping zone setup page in the final step of the wizard?

**Comment by ottok** [comment]
It would really help if @joosev would finally release the setup instruction video so it would be explicit on how current users are expected to start out. Now there is too little documentation and too much guesswork. I think there is already some version of the video. I suggest you just publish that now, and then later iterate and publish another video when you have time.

**Comment by joosev** [comment]
It should not activate pakettikauppa shipping method, because it is not something people should be using. I have actually disabled it in the latest (2.0.19) version by default. I have video almost ready, I will soon upload and send a link to you.

**Comment by l3ku** [comment]
@joosev any updates on the setup instruction video? It would certainly help in the implementation of the wizard, which is waiting at https://github.com/Seravo/woo-pakettikauppa/tree/feature/setup-wizard.
