### ISSUE TITLE
Set shipping parcel volume based on real package volume

### ISSUE THREAD

**Issue by l3ku** [Pakettikauppa/woo-pakettikauppa#22]
Currently, the plugin merely sets the parcel volume as the total volume of the product volumes combined. This is most likely not correct behaviour as the parcel volume depends on the package box volume, which is almost always larger than the total product volume.

However, the plugin should somehow be able to retrieve the parcel size information from the Pakettikauppa API, but it currently does not return any information regarding shipment package box sizes based on total product volume.

**Comment by joosev** [comment]
Could this be solved by having a setting called "minimun parcel volume" or something like "add this much weight and volume to all shipments"?

Good thing is that Pakettikauppa does not require correct weight and volume to be sent, but it does help if it's even close to correct weight (and volume perhaps).

**Comment by joosev** [comment]
Should also pass package dimensions to API (support in API library is coming).

**Comment by joosev** [comment]
Latest version of the api-library (in the dev-branch) should have this feature.

**Comment by joosev** [comment]
This requires some sort of package size support in woo. Passing that information in the api call is trivial, but how in the ui/configs you define package size? And defining package size can not be mandatory because not everyone is using standard size packages.

**Comment by joosev** [comment]
Parcel size can be defined in api-library 2.0

Parcel object has setX , setY and setZ functions
