### ISSUE TITLE
Posti Shippingissä on pakko valita toimituspiste???

### ISSUE THREAD

**Issue by Annasampo** [Pakettikauppa/woo-pakettikauppa#232]
Hei, 
meillä on ongelma Posti Shipping -lisäosan kanssa. Lähetämme tuotteita sekä pakettina että kirjeenä, mutta jos lisäosaan valitsee toimitustavaksi esim. Postipaketin, kassalla on pakko valita toimituspiste. Tämä ei toimi meille. Asiakkaan ei tarvitsisi joutua valitsemaan toimituspistettä, jos tilattu tuote lähetetään joka tapauksessa kirjeenä. Tuotteisiin on merkitty toimitusluokat tuotteen mukaan, mutta vaikka valitsee vain tällaisia tuotteita ostoskoriin, ohjelma pakottaa joka tapauksessa valitsemaan toimituspisteen. 

Lähetämme siis tuotteita nimenomaan postipakettina, jos tuote on sen kokoinen, ettei mahdu kirjeluukusta, joten se olisi oikea valinta toimitustavoista. Nyt olemme laittaneet asetukseksi Pikkupaketti, jossa toimituspisteen valintaa ei siihen tule. Mutta otimme lisäosan käyttöön juuri siksi, että ne asiakkaat, jotka tilaavat pakettina toimitettavan tuotteen, voisivat itse valita toimituspaikan. Lisäosa on meille täysin hyödytön, mikäli sitä ei voi käyttää niin, että tuotteen laadun perusteella voisi määritellä, onko toimituspaikka pakko valita vai ei. Asiakkaille nimittäin on todella hämmentävää, jos he joutuvat valitsemaan toimituspaikaksi postin tai postin automaatin tilaukselle, joka toimitetaan kirjeenä kotiin.

Voitteko selventää, jos vika on käyttäjässä eli minussa (olen kyllä tutkinut kaikki mahdolliset asetusvaihtoehdot) tai korjata, jos vika on sovelluksessa?

Lisäksi on hyvin hämmentävää, että sovellus ohjaa luomaan pakettikortit suoraan WooCommercessa, ilman, että käytössä on integraatio Posti Smartshipiin. Pystyin luomaan pakettikortin, mutta se ei tallennu mihinkään, eikä luo toimitusta postin järjestelmiin (ts. jos olisin yrittänyt lähettää tuotteen, siitä olisi tullut ongelmia). Tuo Smartshipin lisäosa on vieläpä maksullinen, joten Posti tekee valheellista mainontaa, kun väittää, että Shipping on maksuton (mutta tämä ei toki ole teidän ongelmanne, halusin vain tiedottaa). 

Olen yrittänyt selvittää asiaa Postin asiakaspalvelun kautta, mutta he eivät osaa minua auttaa. 

yst.terv.
Anna Martikainen / Nukketeatteri Sampo

**Comment by joosev** [comment]
Toistaiseksi juurikin näin, mutta tuohon on ensi vuonna tulossa muutos. Voit tehdä kaksi eri toimitustapaa woocommercen shipping zoneen ja sitten käyttää jotain conditional shipping pluginia ellei valitsemasi oma toimitushinnoiteluplugin osaa rajoittaa. Eli Kirje toimitustapa näytetään kun kirjetuotteita ja sitten postipaketti kun kyseessä on postipakettituote. Voit sitten määritellä tuolle kirjetoimitukselle että sille ei luoda pakettikorttia ollenkaan.

**Comment by Annasampo** [comment]
Kiitos, sain tämän toimimaan conditional shipping pluginin kanssa, loistavaa!
