### ISSUE TITLE
Pickup point chooser

### ISSUE THREAD

**Issue by joosev** [Pakettikauppa/woo-pakettikauppa#26]
Possibility to search whatever pickup point regardless of the addresses. Only to checkout. This will also solve problems that we are having with Klarna.

**Comment by joosev** [comment]
This means, that there has to be a input field in the checkout to which user can enter any address. Input would use Pakettikauppa API's search Query to find the pickup points.

**Comment by k1sul1** [comment]
Closing this in favour of #93
