### ISSUE TITLE
Shipping Zones suppport

### ISSUE THREAD

**Issue by joosev** [Pakettikauppa/woo-pakettikauppa#27]

**Comment by ottok** [comment]
Potential duplicate https://github.com/Seravo/woo-pakettikauppa/issues/32

**Comment by ottok** [comment]
Related comment: https://github.com/Seravo/woo-pakettikauppa/issues/18#issuecomment-351960497

**Comment by l3ku** [comment]
Implemented in 4fe8cb3ec3a9c280a73efd7201b645fc6be9950f.
