### ISSUE TITLE
Quick action causes exception

### ISSUE THREAD

**Issue by Ciantic** [Pakettikauppa/woo-pakettikauppa#280]
Käytämme pakettikauppaa hieman erikoisella tavalla, millekkään toimitustavalle ei valita pakettikauppaa WC:n asetuksista. Vaan varaston hemmot valitsevat sen jälkeenpäin tilauksen tiedoista (eli asiakas ei valitse sitä kassalla). 

Eli kaikki tilaukset tulee hallintaan oletuksena "Ei toimitusta" valittuna, kuten pitääkin.

Homma toimii, hyvin, mutta yksi nappi on liikaa näkyvissä silloin:

![image](https://user-images.githubusercontent.com/64731/142421650-1ad58ea6-25eb-49cb-95b4-6b41d326dedf.png)

Jos sitä painaa, ja toimitustapaa ei ole valittu tulee tällänen:

```
:  Uncaught Exception: Error: 500, {"printlabel.trackingcode":["Kentt\u00e4 printlabel.trackingcode vaaditaan."]} in wp-content/plugins/woo-pakettikauppa/vendor/pakettikauppa/api-library/src/Pakettikauppa/Client.php:307
Stack trace:
#0 wp-content/plugins/woo-pakettikauppa/core/class-shipment.php(1182): Pakettikauppa\Client->fetchShippingLabels(Array)
#1 wp-content/plugins/woo-pakettikauppa/core/class-admin.php(365): Woo_Pakettikauppa_Core\Shipment->fetch_shipping_labels(Array)
#2 wp-content/plugins/woo-pakettikauppa/core/class-admin.php(353): Woo_Pakettikauppa_Core\Admin->fetch_shipping_labels(Array)
#3 wp-includes/class-wp-hook.php(303): Woo_Pakettikauppa_Core\Admin->create_multiple_shipments('')
#4 wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Ar in 
	wp-content/plugins/woo-pakettikauppa/vendor/pakettikauppa/api-library/src/Pakettikauppa/Client.php
	
 on line 307
```

Ei kovinkaan kriittinen ongelma.

**Comment by joosev** [comment]
Should be fixed in 3.4.0 (currently pending release)
