### ISSUE TITLE
Unable to recreate shipping label

### ISSUE THREAD

**Issue by joosev** [Pakettikauppa/woo-pakettikauppa#3]
Once shipping label is created, cancelling that and creating new one (with modified information) is not possible.

**Comment by l3ku** [comment]
How is this operation handled with the [API client](https://github.com/Pakettikauppa/api-library/blame/master/src/Pakettikauppa/Client.php) in your API-library? Once the tracking code is created by calling `createTrackingCode( $shipment )`, how can I modify the shipment with a certain tracking code so the data is also updated via your API and I can receive the new shipment label? Is it possible to delete a shipment that already has a tracking code and just make a new one? What if the shipment has already been shipped, and the user accidentally creates a new label?

**Comment by joosev** [comment]
At the moment you can't delete shipment through API. So just create new one, old one can be deleted from Pakettikauppa merchant portal.

**Comment by l3ku** [comment]
This is now implemented in c219e1e823470863b1f0ae318fc4e9ec3adba643.
