### ISSUE TITLE
Shipping Zone

### ISSUE THREAD

**Issue by OlikaiDesign** [Pakettikauppa/woo-pakettikauppa#32]
Hello. Have just downloaded this Plugin. I cannot find any documentation anywhere as to how I can make the shipping options in the checkout page only appear for shipping in Finland. The shipping options appear no matter what country is chosen in the checkout.  Can someone please help?

**Comment by joosev** [comment]
This is fixed in plugin version 1.1.0.

**Comment by l3ku** [comment]
Implemented in 4fe8cb3ec3a9c280a73efd7201b645fc6be9950f.
