### ISSUE TITLE
PHP 8 yhteensopivuus

### ISSUE THREAD

**Issue by iljoja** [Pakettikauppa/woo-pakettikauppa#373]
Oheinen muutos olisi tarpeen "posti-shipping/core/class-admin.php" rivillä 103:

Pois:
if (array_key_exists('pakettikauppa_notices', $_SESSION) ) {

Tilalle:
if ($_SESSION !== null && array_key_exists('pakettikauppa_notices', $_SESSION) ) {

Muuten aiheuttaa Fatal Erroria.

**Comment by joosev** [comment]
Korjattu seuraavaan versioon
