### ISSUE TITLE
"Noutopiste" API change

### ISSUE THREAD

**Issue by joosev** [Pakettikauppa/woo-pakettikauppa#4]
Pickup point search API is updated so you can have 1-n predefined providers instead of 1 or all options previously. Module should filter shipping points according to settings page the pickup locations.

**Comment by l3ku** [comment]
@joosev what is the status of this issue? To my understanding there have been plenty of modifications to the order admin edit GUI, but has this been also addressed?

**Comment by joosev** [comment]
This is fixed now by removing the whole feature from admin side.

**Comment by joosev** [comment]
Also fixed in the checkout page by implementing the feature ;D
