### ISSUE TITLE
Invalid accessing of shipping methods via id (should use name)

### ISSUE THREAD

**Issue by ottok** [Pakettikauppa/woo-pakettikauppa#48]
PHP emitted this notice:
```
PHP Notice:  Undefined offset: 1 in /data/wordpress/htdocs/wp-content/plugins/woo-pakettikauppa/includes/class-wc-pakettikauppa.php on line 106
```

Seems to be introduced in commit https://github.com/Seravo/woo-pakettikauppa/commit/26503a9b7b13710c4a16da5845201ac0b2f14640

The line `$shipping_method_id = $shipping_methods[ $chosen_shipping_id ]->instance_settings['shipping_method'];` tries to access shipping methods via id, when it should do it via name instead, since the array has names as keys, not ids.

I don't have time to fix this immediately so filing an issue to not forget the result of my debugging.

**Comment by l3ku** [comment]
Fixed in https://github.com/Seravo/woo-pakettikauppa/commit/65c06e1605d0bfe79485007e0c593322fb96ed8e.
