### ISSUE TITLE
Some shipping methods don't have pickup location

### ISSUE THREAD

**Issue by joosev** [Pakettikauppa/woo-pakettikauppa#5]
Some shipping methods don't have pickup locations, like "Posti pikkupaketti". Now GUI says it has.

**Comment by joosev** [comment]
This is for admin page

**Comment by l3ku** [comment]
Implemented in 66df1d149be57fe0fdd58ca8c22f7e430c49bc14. The admin metabox GUI workflow has been modified so that there is no longer a visible checkbox. Instead, the "Pickup points" selector is hidden/shown automatically depending on if the selected service uses pickup locations.
