### ISSUE TITLE
Settings page has a typo

### ISSUE THREAD

**Issue by joosev** [Pakettikauppa/woo-pakettikauppa#6]
Lisätietoja: Pakettikauppa.fi.

Should read

for example: 
Lisätietoja: Pakettikauppa - www.pakettikauppa.fi

or

Lisätietoja Pakettikaupan kotisivuilta.

or somethign else.

**Comment by l3ku** [comment]
This is now fixed in 2ccb89717fb8c35d8785fb5d59c7de784f86daa8.
