### ISSUE TITLE
Set a minimum supported WooCommerce version into the readme

### ISSUE THREAD

**Issue by l3ku** [Pakettikauppa/woo-pakettikauppa#68]
I recently tested this plugin with an older version 3.3.5 of WooCommerce, which is slightly over a year old. The order admin edit GUI broke due to this with a PHP fatal error:
```
[16-Jul-2019 04:58:28 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method WC_Order_Item_Shipping::get_instance_id() in /data/wordpress/htdocs/wp-content/plugins/woo-pakettikauppa/includes/class-wc-pakettikauppa-admin.php:747
Stack trace:
#0 /data/wordpress/htdocs/wp-content/plugins/woo-pakettikauppa/includes/class-wc-pakettikauppa-admin.php(457): WC_Pakettikauppa_Admin->get_service_id_from_order(Object(WC_Order), false)
#1 /data/wordpress/htdocs/wordpress/wp-admin/includes/template.php(1073): WC_Pakettikauppa_Admin->meta_box(Object(WP_Post), Array)
#2 /data/wordpress/htdocs/wordpress/wp-admin/edit-form-advanced.php(707): do_meta_boxes(Object(WP_Screen), 'side', Object(WP_Post))
#3 /data/wordpress/htdocs/wordpress/wp-admin/post.php(180): include('/data/wordpress...')
#4 {main}
  thrown in /data/wordpress/htdocs/wp-content/plugins/woo-pakettikauppa/includes/class-wc-pakettikauppa-admin.php on line 74
```
This is probably because the function that the plugin uses has been added into the latest releases of WooCommerce, but not the older ones, because updating to WooCommerce 3.6.5 fixed the issue.

If a user with an older version of WooCommerce installs this plugin, his/her site will break. This is why there should be a minimal tested version of WooCommerce stated in the readme that this plugin has been verified to work with.

**Comment by l3ku** [comment]
Seems like we already use the version check provided by WooCommerce (https://woocommerce.wordpress.com/2017/08/28/new-version-check-in-woocommerce-3-2/) in https://github.com/Seravo/woo-pakettikauppa/blob/7972ee8370ca86afa7a042cf06e89fc9db341108/wc-pakettikauppa.php#L13-L14 but having it also in the readme would probably not hurt?

**Comment by ottok** [comment]
Sure, go ahead and add it.
