### ISSUE TITLE
Filter pickup points by COD service availability

### ISSUE THREAD

**Issue by l3ku** [Pakettikauppa/woo-pakettikauppa#80]
Using API testmode and choosing COD as a payment option in the customer checkout, the pickup points are not filtered, but e.g. the "Posti pakettiautomaatti" option can be selected even though it does not support cash-on-delivery. However, when trying to create a package slip for the order in WP admin, the upstream API returns an error response:
![Screen Shot 2019-08-26 at 12 50 12](https://user-images.githubusercontent.com/24781811/63682382-7e896700-c800-11e9-8b78-7104b11abdaa.png)
The plugin should somehow be able to filter the pickup service listing so that the pickup points without COD available should be dropped out so that the unattractive error can be avoided.

**Comment by joosev** [comment]
At the moment Pakettikauppa API does not support this. There is an issue in Pakettikauppa API backlog for this and will be solved somehow... We could in Woo filter the results based on the type of the pickup location, but that might end up showing like 1 or 0 pickup locations. That is why the filtering should be done at API level.
