### ISSUE TITLE
Use WooCommerce shop location instead of having custom settings

### ISSUE THREAD

**Issue by l3ku** [Pakettikauppa/woo-pakettikauppa#81]
This plugin currently has its own settings for the shop location in the "Pakettikauppa" tab in WooCommerce shipping settings. Is there a special shipping-related reason why we can't use the shop location defined in WooCommerce general settings? The user having to enter the shop location into only one place would make simplify the setup of the plugin.

**Comment by joosev** [comment]
There has to be option to override those values. Sometimes there might be a reason for that. By default, it could use the values for store location.
