### ISSUE TITLE
Create a white label fork of this plugin

### ISSUE THREAD

**Issue by ottok** [Pakettikauppa/woo-pakettikauppa#84]
Requirements:
- the fork will be published on wp.org -> needs to have it's own name, `woo-something`
- it has custom branding, so Pakettikauppa.fi will be replaced with something else in all visible UI
- the fork will include only one shipping method provider (defined by Pakettikauppa API), hence the whitelabel branding so that Pakettikauppa.fi is not visible
- needs to be co-installable with this plugin, so
  - plugin name needs to be different
  - main class name needs to be different
  - text domain needs to be different (or user `$this::__CLASS_NAME__` or something)
- custom colors / CSS
- for publishing purposes it also needs to have it's own README.md, readme.txt, composer.json, screenshot.png
- tests must be bootstrapped in some relative way to plugin name so that test code can be void of hard coded plugin or class names

For this to work, we need to:
1. Refactor the plugin so everything is clearly inside one class loaded from wc-pakettikauppa.php. The class code itself needs to be name agnostic and reference itself always with $this or `__CLASS_NAME__` so the class name is not hard-coded anythere.
2. Create a new plugin name and top-level file woo-something.php that will load the same class files as the original plugin, but with a different class name. The new plugin will also have it's own .po files and CSS files, and maybe something more. All new files will have different filenames/paths.
3. When both plugins are developed, the new one can easily be merged since the filenames don't clash and should never create merge conflicts.

**Comment by ottok** [comment]
Clarification to spec: The plugin itself does not need to do any filtering of shipping methods/options. Those will be done automatically by the Pakettikauppa API, which will only offer a subset of shipping options based on what API address is used or what settings a certain API key/account.

The `base_url` for the API needs to be configurable (in code in the white label plugin) so a different Pakettikauppa API address can be used if needed.

**Comment by k1sul1** [comment]
Using a variable / constant / function / etc as the text domain breaks parsers that create the localization files, so that has to be hardcoded. It can always be changed with search-replace later on, assuming it's value is unique.

The whitelabel can have it's own textdomain (which has to be hardcoded as well).

**Comment by joosev** [comment]
> Using a variable / constant / function / etc as the text domain breaks parsers that create the localization files, so that has to be hardcoded. It can always be changed with search-replace later on, assuming it's value is unique.
> 
> The whitelabel can have it's own textdomain (which has to be hardcoded as well).

You are incorrect.

I have tested it:

Code: echo sprintf('<p>%s</p>', __('WooCommerce Pakettikauppa has been installed/updated but no shipping methods are currently active!', self::$module_config['text_domain']));

pot-file:
#: includes/class-wc-pakettikauppa-admin.php:375
msgid "WooCommerce Pakettikauppa has been installed/updated but no shipping methods are currently active!"
msgstr ""


and I used wp's makepot.php to create pot file.

**Comment by k1sul1** [comment]
I use `wp i18n make-pot` and it doesn't work at all without the `--ignore-domains` flag. It "works" with it, but that's a strong case of [_doing_it_wrong()](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#text-domains).

![image](https://user-images.githubusercontent.com/2719615/66913235-e8fa9e80-f01c-11e9-8470-2b94093a6f95.png)

I know from experience that the w.org plugin review team is going to complain about using variables as text domains, and doing so has no apparent benefits that are worth going against the official guidelines.

**Comment by joosev** [comment]
Then I how about putting all the translations on one specific file so only 1 file needs to be handled when updating the plugin?

**Comment by k1sul1** [comment]
What exactly do you mean with that?

On the PHP side? I think it's a good idea to store all text snippets in a class, and then render those by referring to the class (something like `<?php echo $this->core->data->woocommerce_inactive(); ?>` but I think that's out of the scope right now.

Or maybe it isn't, I'll have to edit most of the strings anyway to be able to replace the branding. I'll think about it.
