### ISSUE TITLE
Investigate Google Analytics tracking or other feedback collection methods

### ISSUE THREAD

**Issue by ottok** [Pakettikauppa/woo-pakettikauppa#87]
Documenting this feature request as an issue: Customer asked if the plugin could embed Google Analytics and send GA events on selected actions so data could be collected on how the plugin is used.

We need to check wp.org rules if having a GA embedded in a plugin is allowed and what user consent etc might be needed.

I suspect that is not allowed. If it turns out that way, we should also investigate alternative methods to get the same results: stats/feedback on how users use the plugin.

**Comment by j-falk** [comment]
This got me thinking of two resources that could be looked at:

1) the plugin Beaver Builder has a feature to send usage stats to them if accepted by the user, and it is published on .org, https://wordpress.org/plugins/beaver-builder-lite-version/. Example of the notice the user sees (https://kb.wpbeaverbuilder.com/article/584-anonymous-usage-data-sent-to-beaver-builder) and code for how it is implemented is in "/classes/class-fl-builder-usage.php".

2) Another example which I think is quite popular but also think there has been some negative feedback around how they do it could be freemius, https://freemius.com/wordpress/insights/

Including Google Analytics in a specific plugin on .org or somewhere else is something I have not heard about before.
