### ISSUE TITLE
Display warning if user chooses private pickup point

### ISSUE THREAD

**Issue by joosev** [Pakettikauppa/woo-pakettikauppa#88]
There is a possibility that customer does not know what a private pickup point is. So:
- Put private pickup points as optgroup own group
- Make a confirm dialog (html modal or something) that says what private pickup point is

**Comment by k1sul1** [comment]
`woocommerce_form_field` does not support optgroups. Confirmation modal can be done by hacking around with data attributes.

**Comment by k1sul1** [comment]
![image](https://user-images.githubusercontent.com/2719615/71101029-b86ee680-21be-11ea-9d42-c349bd6f7b4e.png)

What do you want the finnish translation to say @joosev?

**Comment by joosev** [comment]
Valitsemasi noutopiste ei ole julkinen. Oletko varma, että saat noudettua pakettisi?
