### ISSUE TITLE
Uncaught Exception: Error: 541, Invalid postcode: 0000, should be in format of: ##### 

### ISSUE THREAD

**Issue by k1sul1** [Pakettikauppa/woo-pakettikauppa#89]
If WooCommerce is configured with invalid address data, trying to create shipping labels fails miserably without any visible error.

```
Uncaught Exception: Error: 541, Invalid postcode: 0000, should be in format of: ##### in /data/wordpress/htdocs/wp-content/plugins/woo-pakettikauppa/vendor/pakettikauppa/api-library/src/Pakettikauppa/Client.php:87
```

**Comment by joosev** [comment]
It’s invalid postcode ”0000” and that is why it failed. Pakettikauppa API will validate sender and receiver postcode that it is valid.

Also Woocommerce does not provide method to update order comments without reloading the page. That is why when error happens on creating a shipping label, it should reload the page and display error on the order notes.

That is a ”hack” solution to the UX.

**Comment by k1sul1** [comment]
It fails visibly, closing.
