### ISSUE TITLE
 Uncaught Exception: Error: 230, Bad Request: Additional service 3101 specifier codbic empty or missing

### ISSUE THREAD

**Issue by k1sul1** [Pakettikauppa/woo-pakettikauppa#90]
Related to #89 (it's the same process, this just happens later on).

I ordered a package with cash on delivery, but when I tried to create a label for it, I got the the error you see in the title of this issue. I don't know if it's because I'm using test credentials, but this is another fatal error without any message to the user. 

If I change the payment method this issue disappears.

**Comment by joosev** [comment]
If using COD, then you have to define IBAN and BIC in the settings. OTherwise Pakettikauppa API will tell as error message that the IBAN/BIC was missing.

**Comment by k1sul1** [comment]
Yes, that probably fixes it, but there should be an error message nevertheless.
