### ISSUE TITLE
Pickup point search without order information

### ISSUE THREAD

**Issue by joosev** [Pakettikauppa/woo-pakettikauppa#93]
When using Klarna Checkout, pickup point search does not work, because there is no any receiver information.

Create option to allow pickup point search from free text search.

This would bring input element to website where user can input their address information (one text field) and update pickup point list according to the new search parameters.

**Comment by k1sul1** [comment]
I'm having trouble even _trying_ to use Klarna Checkout. Despite using "test mode", it's showing me a very annoying "Klarna Checkout error (Unauthorized)." notification when I try to checkout, without any PHP errors or notices. I also checked the `klarna-checkout-for-woocommerce-2019-11-27-c6481fc9544ef9b10112b89ea4fd27a2.log` on WooCommerce status page, but it's just filled with useless JSON.

I snatched some random credentials from their [API documentation](https://developers.klarna.com/api/#authentication) but that doesn't work. Seems like they want me to create a contract with them to even try it out.

Can you provide me with test credentials that work so I can test that my implementation works on Klarna Checkout as well?
