### ISSUE TITLE
2.1.0 brakes Pakettikauppa shipping method

### ISSUE THREAD

**Issue by joosev** [Pakettikauppa/woo-pakettikauppa#97]
Even though Pakettikauppa shipping method is obsolete, 2.1.0 breaks installations using it.

https://twitter.com/TychoForever/status/1196661671525277697

**Comment by k1sul1** [comment]
Yes, this is the behaviour I described in #96. It should still work on the frontend. It did on my development instance.

**Comment by k1sul1** [comment]
Fixed in #98. Reopen if new issues arise. I hope not.
