### ISSUE TITLE
Setup notification goes undetected

### ISSUE THREAD

**Issue by joosev** [Pakettikauppa/woo-pakettikauppa#99]
When installing plugin, it will show setup wizard notification, but it is way too invisible. It requires more color, images, logos, and bigger text.

**Comment by k1sul1** [comment]
I disagree, I think that you can't miss it, especially after updating to WP 5.3. We can tweak it a bit but there's guidelines on what's ok and what's not. 

https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/#11-plugins-should-not-hijack-the-admin-dashboard

TL;DR don't do what Yoast does. Simply adding a title `WooCommerce Pakettikauppa` to the notice makes it much bigger and thus easier to see. The notice will bug users as long as they haven't configured the plugin, so I think it's a non issue. 

![Screenshot_20191127_144409](https://user-images.githubusercontent.com/2719615/69724352-705f2580-1124-11ea-9680-003fd4680ce3.png)

**Comment by joosev** [comment]
WPML has this kind of a notification:

![Näyttökuva 2019-12-2 kello 13 04 24](https://user-images.githubusercontent.com/14106091/69964481-31154800-151b-11ea-9c3d-d94101299f0d.png)

**Comment by joosev** [comment]
No one seems to notice that there even is a setup wizard available.

**Comment by joosev** [comment]
Maybe pakettikauppa settings page could also display big fat notice on it's setting page that "RUN WIZARD"?

**Comment by k1sul1** [comment]
Closed in #117
